# Generated by Django 4.2.5 on 2023-10-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('years_of_experience', models.IntegerField()),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Finance', 'Finance')], max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
